### ISSUE TITLE
User Registration Testing

### ISSUE THREAD

**Issue by gaishimo** [orangesys/app.orangesys.io#30]
http://nightwatchjs.org/ 等を利用し、ユーザ登録処理の部分のテストを作成する

**Comment by gavinzhou** [comment]
chrome headlessが良さそうです
https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by gavinzhou** [comment]
- [ ] stripe test account にユーザー登録
- [ ] orangeapiにhelm release `circleci-test`  
- [ ] `helm del --purge circleci-test` 削除
