### ISSUE TITLE
解約ボタン

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#34]
途中契約しでも、一ヶ月料金をいただけるよう方針です。
解約月、月末締め、翌月払いとなります。
翌月請求成立後、カード情報を削除します。

[Canceling and Pausing Subscriptions](https://stripe.com/docs/subscriptions/canceling-pausing)

[Firebase でユーザーを管理する  |  Firebase](https://firebase.google.com/docs/auth/web/manage-users#delete_a_user)

**Comment by gaishimo** [comment]
クレジットカードを登録する処理の場合はStripeのPublisable Keyからクレジットカードの情報を元にトークンを作成することができますが、退会の場合Stripeでトークンを作ることができないので認証を別途やらないといけなそうです。

認証するのに、こちらの方法を使ったら良いかと思ったんですがどうでしょうか？
https://firebase.google.com/docs/auth/admin/verify-id-tokens

クライアント側でJWT tokenを生成して、サーバ側でadmin APIをつかってtokenをdecodeする形です。
(ひょっとしたらOrange APIの認証もこちら使った方がよいかもしれません)

**Comment by gavinzhou** [comment]
なるほど、一旦解約ポタンがあれば、
supportメールに連絡でも良いｗｗ

**Comment by gaishimo** [comment]
そんな手がありましたかw

**Comment by gavinzhou** [comment]
最初はminimum viable productでOK
