### ISSUE TITLE
Grafana account information

### ISSUE THREAD

**Issue by gaishimo** [orangesys/app.orangesys.io#37]
Grafanaのアカウント情報を取得しDashboardに表示する。

https://github.com/orangesys/app.orangesys.io/pull/32#issuecomment-261761713

<img width="500" alt="orange_sys" src="https://cloud.githubusercontent.com/assets/4277693/20778372/87e939e6-b7b0-11e6-9c86-8482c7e10224.png">

**Comment by gavinzhou** [comment]
firebaseに保存してる、telegraf.consumerID
```
username : admin 固定
password : 下記の方法と表示します。

node>console.log(new Buffer('<telegraf.consumerID>').toString('base64'));
```
