### ISSUE TITLE
orangesys-srv content must be served over HTTPS.

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#43]
カード登録失敗したが、orangesys-srvへの通信はhttpsが必須

<img width="1167" alt="2016-12-02 23 15 52" src="https://cloud.githubusercontent.com/assets/240780/20836997/5c1446fe-b8e5-11e6-8d2e-324af6cb0da5.png">

orangesys-srvの置き場も考えないといけないかも
おそらく、ssl証明書が必要

**Comment by gavinzhou** [comment]
app.orangesys.ioとorangesys-srvが同じサーバにしよう、検討

**Comment by gavinzhou** [comment]
circle env変更
```
PAYMENT_API_ENDPOINT=https://stripe-orangesys-srv
```

**Comment by gavinzhou** [comment]
clientからstripe apiにアクセスが必要です。
構成を見直します。

```
xhr.js:160 OPTIONS https://stripe-orangesys-srv/customers 

net::ERR_NAME_NOT_RESOLVED(anonymous function)
```

**Comment by gavinzhou** [comment]
orangesys-srvにhttpsの設定したが、下記のエラーを出た。

```
POST https://pay.orangesys.io/customers 400 ()
```

```
"You did not provide an API key, though you did set your Authorization header to "null". Using Bearer auth, your Authorization header should look something like 'Authorization: Bearer YOUR_SECRET_KEY'. See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/."
```

**Comment by gavinzhou** [comment]
SPAのプログラムですが、backend apiに叩くとうまく行けないかも
おそらく、orangeapiも同じ問題かも

**Comment by gavinzhou** [comment]
plan設定後、下記のエラーになりました。
```
"[39] register payment error"
```

**Comment by gavinzhou** [comment]
orangesysにアクセス出来ない状態なら、
登録画面待たずに、dashboardに遷移したい。


<img width="442" alt="2016-12-04 21 02 21" src="https://cloud.githubusercontent.com/assets/240780/20866010/06374d7c-ba65-11e6-9f25-a647d466c576.png">

**Comment by gaishimo** [comment]
> SPAのプログラムですが、backend apiに叩くとうまく行けないかも
おそらく、orangeapiも同じ問題かも
案)
frontとbackendが同じサーバに、
一部backend apiに叩く部分がorangesys-srvへ実装

うまくいかない場合の原因って何でしょうか？ CORSでしょうか？

**Comment by gavinzhou** [comment]
stripeのapiと同じ、SPAは全てclient側を実行しますから
内部IPにアクセスできない原因かな

**Comment by gavinzhou** [comment]
これかなぁ
```
PAYMENT_API_ENDPOINT=https://PAYMENT_API_ENDPOINT
ORANGESYS_API_ENDPOINT=https://ORANGESYS_API_ENDPOINT
```
```
PAYMENT_API_ENDPOINT=https://pay.orangesys.io に変更しました。行けました。
ORANGESYS_API_ENDPOINT=https://sys-orangeapi   ← ここにアクセスできない
```
clientからsys-orangeapiにアクセスできない、内部IPだから、domainにしたら、行けると思う。
```
sys-orangeapi          10.3.253.171   <none>            80/TCP              4d
```

セキュリティ問題が出てきますね

**Comment by gavinzhou** [comment]
一連作業確認しました。
googleアカウント登録、plan及びカード登録、環境構築
