### ISSUE TITLE
change backend api

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#45]
参照
#7 #18 

下記のような流れ、変更がいかがでしょうか

1. planを選択し、カード登録後、stripe関連情報をfirebaseに保存
>- planID
>- customerId
>- retention

2. 1.がOKなら、下記のAPIへ送信します、responseが200
```
http POST "http://127.0.0.1:1323/create?uuid=BTIHEoKPwscQqiLwe8dJpleD8FC3&rp=10d"
```
uuidはfirebaseに登録後、自動付与された部分です。
```
https://saas-orangesys-io.firebaseio.com/users/BTIHEoKPwscQqiLwe8dJpleD8FC3
```

3. 2がOKなら、登録画面画面から、dashboardへ遷移

4. 30秒ぐらい、influxdbへping出来たら、updatedAtを更新します。（以前と同じ処理）

- orangeapiからuuidをfirebaseに確認し、ユーザー存在する場合は、環境構築します。
- jwt tokenをfirebaseに書き込みします。

**Comment by gaishimo** [comment]
問題ないと思います!

**Comment by gavinzhou** [comment]
orangeapiの修正が一旦完了です。

https://github.com/orangesys/orangeapi/issues/2

**Comment by gavinzhou** [comment]
一連作業確認しました。
googleアカウント登録、plan及びカード登録、環境構築
