### ISSUE TITLE
Firebase configuration - verification email template

### ISSUE THREAD

**Issue by gaishimo** [orangesys/app.orangesys.io#48]
@gavinzhou 
Firebase認証のEmail Verificationで以下の設定をする必要があります。

<img width="500" alt="firebase_mail_config" src="https://cloud.githubusercontent.com/assets/4277693/20995993/dd3d5ffc-bd3d-11e6-861e-e0ddd7891149.png">

Email、もしくはGithubアカウントでユーザ登録した時Email認証のメールがユーザに飛ぶのですが、デフォルトのままだと問題があるため、Orangesysのアプリ画面にリンクで飛ばすようにする必要があります。

APP_LINKで `https://servername#/verify` を指定すればOKです。

参考: https://github.com/orangesys/app.orangesys.io/issues/5

**Comment by gavinzhou** [comment]
@gaishimo 
templateを修正した、ご確認をお願いいたします。

**Comment by gaishimo** [comment]
あ、すみません、servernameの部分、`app.orangesys.io` にしないといけないです。

**Comment by gavinzhou** [comment]
```
https://app.orangesys.io#/verify
```
この感じでしょうか

**Comment by gaishimo** [comment]
はい、そうです 👌

**Comment by gavinzhou** [comment]
修正した、いかがですか

**Comment by gaishimo** [comment]
問題ないです 👍 ありがとうございます。
