### ISSUE TITLE
duplicate stripe event

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#49]
1. stripe eventへの登録OK
2. orangeapiへ失敗

app.oragnesys.ioにアクセスすると、カード再登録になり

再登録もできます。
2重請求になります。

**Comment by gaishimo** [comment]
あれ、stripeで登録したタイミングでFirebaseにcustomerId等が入るので2重にはならないはずなんですが。。

**Comment by gavinzhou** [comment]
すみません、ざっくりテストしたか
夜もう一度テストします

**Comment by gavinzhou** [comment]
slackのmonitorを確認した、自分の勘違い、すみませんでした
