### ISSUE TITLE
progress bar faster

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#50]
progress barが早すぎるｗｗ
スピード落とし

<img width="548" alt="2016-12-09 0 31 21" src="https://cloud.githubusercontent.com/assets/240780/21015877/ec457412-bda6-11e6-83e1-7230d91cb644.png">

**Comment by gaishimo** [comment]
これ、以外と手間がかかりそうです。Componentのアニメーションスピードが固定になってしまっているので。。
https://github.com/callemall/material-ui/blob/master/src/LinearProgress/LinearProgress.js#L45

**Comment by gaishimo** [comment]
こちらに変えてしまうのもありかもしれません。
http://www.material-ui.com/#/components/circular-progress

**Comment by gavinzhou** [comment]
@gaishimo 
環境構築環境確認方法
テスト時に、通信は一旦httpします。
後ほど、証明書を設定します。
```
curl -I http://<telegraf.consumerID>.i.orangesys.io/ping\?jwt\=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhZDgwYzRhNWJjYjI0MzQ1ODBjMDAyYjliMDhkMDI2MyJ9.Bk9wz0t9vwBIQQpt-Zmn3qBVosmCdi7ja0oeXa_bUEY
```
