### ISSUE TITLE
support mail set

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#52]
- 構築失敗などの問い合わせメールは
「support@orangesys.io」を表示します。

- 最初のプラン変更はサポートメールに連絡すれば、良いです。

**Comment by gaishimo** [comment]
@gavinzhou これは具体的に何をするんでしょうか？

構築失敗した時とかに画面に"`support@orangesys.io` にお問い合わせください" というようなメッセージを表示させるという感じでしょうか？

**Comment by gavinzhou** [comment]
これでOKです
