### ISSUE TITLE
duplicate access orangeapi by create use

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#69]
ユーザー作成時、2回orangeapiへ叩いた

構築は2回走られ、構築失敗statusを反映した

```
~ ❯❯❯ k get pod
NAME                               READY     STATUS    RESTARTS   AGE
bzayzn-grafana-863318141-iupmt     1/1       Running   0          1m
bzayzn-grafana-rrqav               0/1       Pending   0          1m
bzayzn-influxdb-1279533267-g9n29   0/1       Pending   0          1m
bzayzn-influxdb-dya4e              1/1       Running   0          1m
iuhpoq-grafana-3435475016-rdd8j    1/1       Running   0          1m
iuhpoq-influxdb-1409622182-bi604   1/1       Running   0          1m
```

<img width="725" alt="2016-12-30 13 40 15" src="https://cloud.githubusercontent.com/assets/240780/21559766/96dca9be-ce95-11e6-845f-bff5b8c3683e.png">

**Comment by gaishimo** [comment]
これ、ローカルで動作確認できないと確認不足で同じような問題が発生しそうな気がするので、簡単なmockサーバ作って動作確認出来るようにしたいと思います :octocat:

**Comment by gavinzhou** [comment]
fake apiで確認できないでしょうか？
Sleep 6sくらいを入れ、access log確認感じ

**Comment by gaishimo** [comment]
了解です。とりあえずfake api で一度確認してみます。

**Comment by gavinzhou** [comment]
orangeapiを作り直しました
https://github.com/orangesys/orangeapi
pythonのコードを全部golangで作り直した。
以前より、dataflowがシンプルにしたが、実行時間が約5sになりました。

**Comment by gaishimo** [comment]
おお、たくさん修正されてる 🤓
