### ISSUE TITLE
duplicate login

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#72]
google登録されてる状態で、パスワードリセットを行うと2重登録状態となります。

※google登録後、githubで同じメアドで登録出来ないから、メアドの唯一になりますね。

<img width="594" alt="2017-01-03 18 49 46" src="https://cloud.githubusercontent.com/assets/240780/21604323/eb419156-d1e5-11e6-946f-18232b733fce.png">

**Comment by gaishimo** [comment]
Emailでユーザ登録した後Googleでユーザ登録した場合も同じような状態になりますね 🌵 
こういう状態になるのは気づいていたんですが、アカウントは同一のものなのでログイン手段が複数あっても特に害はないかと思って気にしてませんでした 👀 

Firebaseのデフォルトの設定が「1 つのメールアドレスにつき 1 つのアカウント」というふうになっているんですが、外部プロバイダの場合は1つしか使えないという意味ではないかと思っています。

（もう少しドキュメントをしっかり確認した方がいいかもしれませんが..)

**Comment by gavinzhou** [comment]
そうです、docsを確認しましょ、とりあえず、対応しなくでもよい

**Comment by gaishimo** [comment]
memo:

確認したところ、ユーザ登録時の動作はGoogleアカウントだけ特別扱いになっている感じでした。

既にEmailを使って登録している場合、同じEmailのGithubのアカウントで登録しようとするとFirebase APIからエラー`auth/account-exists-with-different-credential`が戻ってくるんですが、Googleアカウントで登録しようとした場合はエラーなしでそのまま登録できる感じになっていました。

また、Firebase Consoleの設定で
「同一のメールアドレスを使用して複数のアカウントを作成できるようにする」
という設定がありますが、これは同じEmailの別の外部アカウントを使って新しく別のユーザを作ることができるかどうかを整理するためのものでした。


一つのアカウントが複数ログイン方法をもつこと自体は問題なさそうです。
いずれログイン後の画面でアカウント連携の管理ができると良さそうです。
たとえばGoogleでログインしているけど別のGoogleアカウントに変更したい場合とかは、
一度Emailでのログイン方法を追加した後、Googleの連携を解除して、別のGoogleアカウントでまた連携する みたいなことができれば便利かと思います。
