### ISSUE TITLE
create contact form

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#84]
emailへの連絡が「contact form」に変更しようと思います。

**Comment by gaishimo** [comment]
formをsubmitしたらどう通知しましょうかね?
メールそれともSlack通知とかがいいですかね?

**Comment by gavinzhou** [comment]
メールの連絡がOKです

**Comment by gaishimo** [comment]
SMTPサーバはどうしましょうかね?

**Comment by gavinzhou** [comment]
そっか、
外部のsmtpを利用しないといけないですね
spaだから、tokenが名文化になるか

**Comment by gaishimo** [comment]
@gavin このフォームはログインしていないユーザにも利用できるようにしますか? それとも基本的にはログイン済み(ユーザ登録済み)のユーザのみとなりますか？

**Comment by gavinzhou** [comment]
登録済みのユーザ限定で良いです
タイミングによって、カスタマサポートツールを入れようと考えます。
一旦シンプルなお問い合わせフォームが問題ないです
