### ISSUE TITLE
Add Google Analytics configuration

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/app.orangesys.io#87]
dummy userを削除のため、app.orangesys.ioにログイン時間を記載してほしい
同じ効果があれば、別の方法でも良いです。

**Comment by gaishimo** [comment]
これ、Login時というより、アクセスがあったら保存という感じで大丈夫ですかね?
(Cookieにログイン情報が保存されている場合、ログインのアクションを行わないので)

**Comment by gavinzhou** [comment]
- app画面の利用頻度を把握したいです
`google analytics`  を入れた方が良さそうか？

**Comment by gaishimo** [comment]
すみません、ちょっと曖昧でわからなくなって来たんですが、以下のような意味ですか?  😓 

 - ダミーユーザを削除する時にわかりやすくするしたい -> 最新のログイン時間をDBに保存しておく
 - アプリの利用頻度を把握する -> アクセス時間を保存しておく or Google Analyticsを利用

**Comment by gavinzhou** [comment]
いえいえ、説明足りない

- アプリの利用頻度を把握する -> アクセス時間を保存しておく or Google Analyticsを利用

これで良い

dummy userを削除時、現状のDB情報が十分かなあ

**Comment by gavinzhou** [comment]
一旦、google analyticsに入れるか？

**Comment by gaishimo** [comment]
そうですね、頻度を知りたいだけならGoogle Analyticsでいいんじゃないかと思います。

DBにも最新のアクセス時間だけは保存しとくといいかもしれませんが。

**Comment by gavinzhou** [comment]
とりあえず、GAにしましょ

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74389152-2', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by gaishimo** [comment]
``
